defaults: &defaults
  showmap: true
  # values should be between 1 and 100
  access_point_pagination: [
    { value: 10, default: false },
    { value: 20, default: true },
    { value: 50, default: false },
    { value: 100, default: false }
  ]
  showstatus: false

  max_threads: 10          #Number of threads
  ping_timeout: 5          #Minutes between pings
  housekeeping_interval: 6 #Months for the housekeeping

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
